# Generated by Django 6.1 on 2026-09-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChargeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_to_1kg', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('up_to_3kg', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('up_to_5kg', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('above_5kg', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Charge Rate',
                'verbose_name_plural': 'Delivery Charge Rates',
            },
        ),
    ]
